### ISSUE TITLE
Mention Drupal VM setup?

### ISSUE THREAD

**Issue by geerlingguy** [klausi/pareviewsh#9]
Through https://github.com/geerlingguy/drupal-vm/issues/1197, I implemented pretty simple support for PAReview.sh in Drupal VM, and setup is simply adding the following to `config.yml`:

```yaml
post_provision_scripts:
  - "../examples/scripts/pareview.sh"

composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }
  - { name: drupal/coder, release: '^8.2' }

nodejs_version: "6.x"
nodejs_npm_global_packages:
  eslint
```

Then after `vagrant up`, you can `vagrant ssh` into Drupal VM and run any of the typical commands:

```
$ pareview.sh /path/to/my/module
$ pareview.sh http://git.drupal.org/project/rules.git 8.x-1.x
```

This might be easier setup for someone newer to Drupal/dev than having them install a python project via pip, node.js npm project, a composer project, etc., then building all the symlinks and such by hand.
